MissionItem(
    latitude_deg=lat,
    longitude_deg=lon,
    relative_altitude_m=rel_alt,
    speed_m_s=speed,
    is_fly_through=True,
    gimbal_pitch_deg=0.0,
    gimbal_yaw_deg=0.0,
    camera_action=MissionItem.CameraAction.NONE,
    loiter_time_s=0.0,
    camera_photo_interval_s=0.0,
    acceptance_radius_m=2.0,
    yaw_deg=float("nan"),
    camera_photo_distance_m=0.0,
    vehicle_action=MissionItem.VehicleAction.NONE
)
