name: Python CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # לא מתקינים mavsdk ותלויות כבדות; רק כלים סטטיים
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.9 flake8==7.1.1

      # בדיקת תחביר/סטייל (לא מייבא מודולים)
      - name: Ruff (lint)
        run: ruff check .

      - name: Flake8 (light)
        run: flake8 --exclude .venv,build,dist --max-line-length=120

      # בדיקת קומפילציה בלי להריץ (תופס שגיאות תחביר)
      - name: Syntax check (compileall)
        run: python -m compileall -q src || (echo "Syntax errors found" && exit 1)
